/**
 * @file src/components/FiringLetterCard.tsx
 * @description Generates a firing letter image for sharing
 * @platform React Native (Expo)
 * @spec PLAN/SPECS/spec-005-social.md
 */

import React, { forwardRef } from 'react';
import { View, Text, StyleSheet, Image } from 'react-native';
import ViewShot from 'react-native-view-shot';
import { FiringLetterData } from '../types/game.types';

interface Props {
  data: FiringLetterData;
}

export const FiringLetterCard = forwardRef<ViewShot, Props>(({ data }, ref) => {
  return (
    <ViewShot ref={ref} options={{ format: 'png', quality: 0.9 }}>
      <View style={styles.card}>
        <View style={styles.header}>
          <Text style={styles.companyName}>SYNERGY DYNAMICS INC</Text>
          <View style={styles.divider} />
          <Text style={styles.noticeTitle}>TERMINATION NOTICE</Text>
        </View>

        <View style={styles.body}>
          <Text style={styles.text}>Dear {data.playerName},</Text>
          <Text style={styles.text}>Your employment has been terminated for:</Text>
          <Text style={styles.reason}>"{data.terminationReason}"</Text>
          
          <View style={styles.statsContainer}>
            <View style={styles.statRow}>
              <Text style={styles.statLabel}>Days Survived:</Text>
              <Text style={styles.statValue}>{data.daysSurvived}</Text>
            </View>
            <View style={styles.statRow}>
              <Text style={styles.statLabel}>Chaos Caused:</Text>
              <Text style={styles.statValue}>{data.chaos}%</Text>
            </View>
            <View style={styles.statRow}>
              <Text style={styles.statLabel}>Final Reputation:</Text>
              <Text style={styles.statValue}>{data.reputation}%</Text>
            </View>
          </View>

          <Text style={styles.footerText}>Please return your stapler.</Text>
          
          <View style={styles.signatureBlock}>
            <Text style={styles.text}>Regards,</Text>
            <Text style={styles.signature}>HR Bot #4729</Text>
          </View>
        </View>
        
        <View style={styles.branding}>
          <Text style={styles.brandingText}>Generated by Corporate Chaos</Text>
        </View>
      </View>
    </ViewShot>
  );
});

const styles = StyleSheet.create({
  card: {
    width: 350,
    backgroundColor: '#fff',
    padding: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  header: {
    alignItems: 'center',
    marginBottom: 24,
  },
  companyName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    letterSpacing: 2,
  },
  divider: {
    height: 2,
    backgroundColor: '#000',
    width: '100%',
    marginVertical: 12,
  },
  noticeTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#d32f2f',
    textDecorationLine: 'underline',
  },
  body: {
    gap: 16,
  },
  text: {
    fontSize: 16,
    color: '#333',
    fontFamily: 'monospace',
  },
  reason: {
    fontSize: 18,
    fontWeight: 'bold',
    fontStyle: 'italic',
    color: '#000',
    textAlign: 'center',
    marginVertical: 12,
    paddingHorizontal: 10,
  },
  statsContainer: {
    backgroundColor: '#f5f5f5',
    padding: 16,
    borderWidth: 1,
    borderColor: '#ddd',
    marginVertical: 16,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  statLabel: {
    fontSize: 14,
    color: '#666',
    fontFamily: 'monospace',
  },
  statValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    fontFamily: 'monospace',
  },
  footerText: {
    fontSize: 14,
    color: '#555',
    fontStyle: 'italic',
    marginTop: 8,
  },
  signatureBlock: {
    marginTop: 24,
  },
  signature: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    fontFamily: 'monospace',
    marginTop: 4,
  },
  branding: {
    marginTop: 24,
    alignItems: 'center',
  },
  brandingText: {
    fontSize: 10,
    color: '#999',
  },
});

